"""OCP (OpenCascade) Python code generator from PolyScript AST."""

from __future__ import annotations

import enum
from . import ast_nodes as ast
from .colors import resolve_color
from .errors import CodegenError


class PipelineContext(enum.Enum):
    """Context type flowing through a pipeline."""
    WORKPLANE = "Workplane"
    TWO_D = "2D"
    THREE_D = "3D"
    FACE_SELECTION = "FaceSelection"
    EDGE_SELECTION = "EdgeSelection"
    VERTEX_SELECTION = "VertexSelection"
    POINT_SELECTION = "PointSelection"
    UNKNOWN = "unknown"


# 2D primitive names for error messages
_2D_PRIMITIVE_NAMES = {
    ast.Circle: "circle",
    ast.Rect: "rect",
    ast.Ellipse: "ellipse",
    ast.Polyline: "polyline",
    ast.Polygon: "polygon",
    ast.Text: "text",
    ast.SketchExpr: "sketch",
}


_MATH_FUNCS = {
    "sin", "cos", "tan", "asin", "acos", "atan", "atan2",
    "sqrt", "radians", "degrees", "floor", "ceil",
}
_MATH_ALIASES = {"rad": "radians", "deg": "degrees"}

# Selector name aliases -> shorthand notation
_SELECTOR_NAME_ALIASES = {
    "top": ">Z", "bottom": "<Z",
    "right": ">X", "left": "<X",
    "front": ">Y", "back": "<Y",
}

# Selector symbol mapping: PolyScript symbol -> CadQuery selector symbol
_SELECTOR_SYMBOL_MAP = {
    ">": ">",   # max position
    "<": "<",   # min position
    "=": "|",   # parallel
    "+": "#",   # perpendicular
}


def _selector_to_cadquery(sel: str) -> str:
    """Convert a PolyScript selector to a CadQuery selector string.

    Examples:
        ">Z"   -> ">Z"
        "=Z"   -> "|Z"
        "+Z"   -> "#Z"
        "top"  -> ">Z"
        "front" -> ">Y"
    """
    # Resolve name aliases first
    if sel in _SELECTOR_NAME_ALIASES:
        sel = _SELECTOR_NAME_ALIASES[sel]
    # Map symbol if needed
    if len(sel) >= 2 and sel[0] in _SELECTOR_SYMBOL_MAP:
        return _SELECTOR_SYMBOL_MAP[sel[0]] + sel[1:]
    return sel


class OCPCodegen:
    """Generate OCP Python code from a PolyScript AST."""

    _HEADER = [
        "# Generated by PolyScript (OCP backend)",
        "from polyscript import ocp_kernel as cq",
        "import math",
        "",
    ]

    def __init__(self):
        self.lines: list[str] = []
        self.indent = 0
        self._var_counter = 0
        self._result_var = "_result"
        self._functions: dict[str, ast.FuncDef] = {}

    def generate(self, program: ast.Program) -> str:
        self.lines = list(self._HEADER)

        # First pass: collect function definitions
        for stmt in program.statements:
            if isinstance(stmt, ast.FuncDef):
                self._functions[stmt.name] = stmt

        # Generate code
        shape_vars: list[str] = []
        for stmt in program.statements:
            if isinstance(stmt, ast.FuncDef):
                self._gen_funcdef(stmt)
            elif isinstance(stmt, ast.Assignment):
                self._gen_assignment(stmt)
            else:
                var = self._new_var()
                expr_code = self._gen_expr(stmt)
                self._emit(f"{var} = {expr_code}")
                shape_vars.append(var)

        if len(shape_vars) > 1:
            self._emit("")
            self._emit(f"_result = {shape_vars[0]}")
            for v in shape_vars[1:]:
                self._emit(f"_result = _result.union({v})")
        elif len(shape_vars) == 1:
            self._emit("")
            self._emit(f"_result = {shape_vars[0]}")
        else:
            self._emit("_result = None")

        return "\n".join(self.lines)

    def _emit(self, line: str):
        self.lines.append("    " * self.indent + line)

    def _new_var(self) -> str:
        self._var_counter += 1
        return f"_v{self._var_counter}"

    # --- Top Level ---

    def _gen_funcdef(self, node: ast.FuncDef):
        params = ", ".join(node.params)
        self._emit(f"def {node.name}({params}):")
        self.indent += 1
        body_code = self._gen_expr(node.body)
        self._emit(f"return {body_code}")
        self.indent -= 1
        self._emit("")

    def _gen_assignment(self, node: ast.Assignment) -> str:
        expr_code = self._gen_expr(node.value)
        self._emit(f"{node.name} = {expr_code}")
        return node.name

    # --- Expression Dispatch ---

    def _expr_number_lit(self, node: ast.NumberLit) -> str:
        return repr(node.value)

    def _expr_string_lit(self, node: ast.StringLit) -> str:
        return repr(node.value)

    def _expr_var_ref(self, node: ast.VarRef) -> str:
        return node.name

    def _expr_tag_ref(self, node: ast.TagRef) -> str:
        return repr(node.name)

    def _expr_bin_op(self, node: ast.BinOp) -> str:
        return f"({self._gen_expr(node.left)} {node.op} {self._gen_expr(node.right)})"

    def _expr_unary_neg(self, node: ast.UnaryNeg) -> str:
        return f"(-{self._gen_expr(node.operand)})"

    def _expr_tuple_lit(self, node: ast.TupleLit) -> str:
        vals = ", ".join(self._gen_expr(v) for v in node.values)
        return f"({vals})"

    def _expr_list_lit(self, node: ast.ListLit) -> str:
        vals = ", ".join(self._gen_expr(v) for v in node.values)
        return f"[{vals}]"

    def _expr_if_expr(self, node: ast.IfExpr) -> str:
        c = self._gen_expr(node.cond)
        t = self._gen_expr(node.then_expr)
        e = self._gen_expr(node.else_expr)
        return f"({t} if {c} else {e})"

    def _expr_bool_const(self, node: ast.BoolConst) -> str:
        return "True" if node.value else "False"

    def _expr_selector_lit(self, node: ast.SelectorLit) -> str:
        return repr(_selector_to_cadquery(node.value))

    _EXPR_DISPATCH: dict[type, str] = {
        ast.Pipeline:      "_gen_pipeline",
        ast.NumberLit:     "_expr_number_lit",
        ast.StringLit:     "_expr_string_lit",
        ast.VarRef:        "_expr_var_ref",
        ast.TagRef:        "_expr_tag_ref",
        ast.BinOp:         "_expr_bin_op",
        ast.UnaryNeg:      "_expr_unary_neg",
        ast.TupleLit:      "_expr_tuple_lit",
        ast.ListLit:       "_expr_list_lit",
        ast.ListComp:      "_gen_list_comp",
        ast.IfExpr:        "_expr_if_expr",
        ast.BoolConst:     "_expr_bool_const",
        ast.SelectorLit:   "_expr_selector_lit",
        ast.Box:           "_gen_box",
        ast.Cylinder:      "_gen_cylinder",
        ast.Sphere:        "_gen_sphere",
        ast.Cone:          "_gen_cone",
        ast.Torus:         "_gen_torus",
        ast.Wedge:         "_gen_wedge",
        ast.Rect:          "_gen_rect",
        ast.Circle:        "_gen_circle",
        ast.Ellipse:       "_gen_ellipse",
        ast.Polyline:      "_gen_polyline",
        ast.Polygon:       "_gen_polygon",
        ast.Text:          "_gen_text",
        ast.Union:         "_gen_union_source",
        ast.Diff:          "_gen_diff_source",
        ast.Inter:         "_gen_inter_source",
        ast.FuncCall:      "_gen_func_call",
        ast.LinePath:      "_gen_line_path",
        ast.ArcPath:       "_gen_arc_path",
        ast.HelixPath:     "_gen_helix_path",
        ast.BezierPath:    "_gen_bezier_path",
        ast.SplinePath:    "_gen_spline_path",
        ast.SketchExpr:    "_gen_sketch",
    }

    def _gen_expr(self, node: ast.Node) -> str:
        if node is None:
            return "None"
        handler_name = self._EXPR_DISPATCH.get(type(node))
        if handler_name is None:
            raise CodegenError(f"Unknown expression node: {type(node).__name__}")
        return getattr(self, handler_name)(node)

    # --- Pipeline Context Tracking ---

    @staticmethod
    def _source_context(source: ast.Node) -> PipelineContext:
        """Determine the pipeline context from the source node."""
        if isinstance(source, (ast.Box, ast.Cylinder, ast.Sphere, ast.Cone, ast.Torus)):
            return PipelineContext.THREE_D
        if isinstance(source, (ast.Rect, ast.Circle, ast.Ellipse,
                               ast.Polyline, ast.Polygon, ast.Text,
                               ast.SketchExpr)):
            return PipelineContext.TWO_D
        if isinstance(source, (ast.LinePath, ast.ArcPath, ast.BezierPath,
                               ast.HelixPath, ast.SplinePath)):
            return PipelineContext.TWO_D
        if isinstance(source, (ast.Union, ast.Diff, ast.Inter)):
            return PipelineContext.THREE_D
        # VarRef, FuncCall, etc. -- cannot statically determine
        return PipelineContext.UNKNOWN

    @staticmethod
    def _op_output_context(op: ast.Node, current_ctx: PipelineContext) -> PipelineContext:
        """Determine the output context after applying a pipe operation."""
        if isinstance(op, ast.FacesSelect):
            return PipelineContext.FACE_SELECTION
        if isinstance(op, ast.EdgesSelect):
            return PipelineContext.EDGE_SELECTION
        if isinstance(op, ast.VerticesSelect):
            return PipelineContext.VERTEX_SELECTION
        if isinstance(op, ast.PointsSelect):
            return PipelineContext.POINT_SELECTION
        if isinstance(op, ast.Workplane):
            return PipelineContext.WORKPLANE
        if isinstance(op, ast.Place):
            return PipelineContext.TWO_D
        if isinstance(op, ast.Implicit2DPrimitive):
            return PipelineContext.TWO_D
        if isinstance(op, ast.Implicit3DPrimitive):
            return PipelineContext.THREE_D
        if isinstance(op, (ast.Extrude, ast.Revolve, ast.Sweep, ast.Loft, ast.Cut)):
            return PipelineContext.THREE_D
        if isinstance(op, ast.Hole):
            return PipelineContext.THREE_D
        if isinstance(op, (ast.Fillet, ast.Chamfer)):
            # fillet/chamfer from selection contexts -> 3D; from 2D -> 2D
            if current_ctx == PipelineContext.TWO_D:
                return PipelineContext.TWO_D
            return PipelineContext.THREE_D
        if isinstance(op, ast.Shell):
            return PipelineContext.THREE_D
        if isinstance(op, ast.Offset):
            return PipelineContext.TWO_D
        if isinstance(op, (ast.Diff, ast.Union, ast.Inter)):
            return PipelineContext.THREE_D
        if isinstance(op, (ast.Grid, ast.Polar)):
            if current_ctx in (PipelineContext.FACE_SELECTION, PipelineContext.POINT_SELECTION):
                return PipelineContext.POINT_SELECTION
            return current_ctx
        if isinstance(op, (ast.Translate, ast.Rotate, ast.Scale, ast.Mirror)):
            return current_ctx  # preserves context
        if isinstance(op, ast.ColorOp):
            return current_ctx  # preserves context
        if isinstance(op, (ast.Move, ast.MoveTo)):
            return current_ctx  # 2D context operations
        if isinstance(op, ast.AsTag):
            return current_ctx  # preserves context
        return PipelineContext.UNKNOWN

    @staticmethod
    def _validate_2d_primitive_context(
        op: ast.Implicit2DPrimitive, ctx: PipelineContext
    ) -> None:
        """Raise CodegenError if a 2D primitive appears in an invalid context."""
        # Contexts that allow 2D primitives:
        # Workplane, FaceSelection (implicit workplane), VertexSelection, PointSelection, 2D, unknown
        if ctx in (
            PipelineContext.THREE_D,
            PipelineContext.EDGE_SELECTION,
        ):
            prim_name = _2D_PRIMITIVE_NAMES.get(
                type(op.primitive), type(op.primitive).__name__.lower()
            )
            raise CodegenError(
                f"2D primitive '{prim_name}' requires face selection. "
                f"Use '| faces top |' or similar before '| {prim_name} ...'"
            )

    # 3D primitive names for error messages
    _3D_PRIMITIVE_NAMES = {
        ast.Box: "box",
        ast.Cylinder: "cylinder",
        ast.Sphere: "sphere",
        ast.Cone: "cone",
        ast.Torus: "torus",
    }

    @staticmethod
    def _validate_3d_primitive_context(
        op: ast.Implicit3DPrimitive, ctx: PipelineContext
    ) -> None:
        """Raise CodegenError if a 3D primitive appears in an invalid pipe context."""
        # 3D primitives in pipes are only allowed in VertexSelection or PointSelection
        allowed = (
            PipelineContext.VERTEX_SELECTION,
            PipelineContext.POINT_SELECTION,
        )
        if ctx not in allowed:
            prim_name = OCPCodegen._3D_PRIMITIVE_NAMES.get(
                type(op.primitive), type(op.primitive).__name__.lower()
            )
            raise CodegenError(
                f"3D primitive '{prim_name}' in pipe requires vertex or point selection. "
                f"Use '| verts |' or '| points ... |' before '| {prim_name} ...'"
            )

    # --- Pipeline ---

    def _gen_pipeline(self, node: ast.Pipeline) -> str:
        code = self._gen_expr(node.source)
        ctx = self._source_context(node.source)
        prev_op = None
        for op in node.operations:
            # Validate 2D primitive context before generating code
            if isinstance(op, ast.Implicit2DPrimitive):
                self._validate_2d_primitive_context(op, ctx)
            if isinstance(op, ast.Implicit3DPrimitive):
                self._validate_3d_primitive_context(op, ctx)
            code = self._gen_pipe_op(code, op, prev_op=prev_op, ctx=ctx)
            ctx = self._op_output_context(op, ctx)
            prev_op = op
        return code

    # Dispatch table mapping AST node types to handler method names.
    # Handlers are called as method(current, op) by default.
    # Handlers listed in _PIPE_CTX_OPS also receive a ctx keyword argument.
    _PIPE_DISPATCH: dict[type, str] = {
        ast.FacesSelect:        "_gen_faces_select",
        ast.EdgesSelect:        "_gen_edges_select",
        ast.VerticesSelect:     "_gen_vertices_select",
        ast.PointsSelect:       "_gen_points_select",
        ast.Workplane:          "_gen_workplane",
        ast.AsTag:              "_gen_as_tag",
        ast.Fillet:             "_gen_pipe_fillet",
        ast.Chamfer:            "_gen_pipe_chamfer",
        ast.Shell:              "_gen_shell",
        ast.Offset:             "_gen_offset",
        ast.Diff:               "_gen_diff",
        ast.Union:              "_gen_union",
        ast.Inter:              "_gen_inter",
        ast.Place:              "_gen_place",
        ast.Hole:               "_gen_hole",
        ast.Cut:                "_gen_cut",
        ast.Extrude:            "_gen_extrude",
        ast.Revolve:            "_gen_revolve",
        ast.Sweep:              "_gen_sweep",
        ast.Loft:               "_gen_loft",
        ast.ColorOp:            "_gen_color",
        ast.Translate:          "_gen_translate",
        ast.Rotate:             "_gen_rotate",
        ast.Scale:              "_gen_scale",
        ast.Mirror:             "_gen_mirror",
        ast.Move:               "_gen_move",
        ast.MoveTo:             "_gen_moveto",
        ast.Implicit2DPrimitive: "_gen_implicit_2d",
        ast.Implicit3DPrimitive: "_gen_implicit_3d",
        ast.Grid:               "_gen_pipe_grid",
        ast.Polar:              "_gen_pipe_polar_op",
    }

    # Subset of _PIPE_DISPATCH whose handlers accept an extra ctx= keyword.
    _PIPE_CTX_OPS: frozenset[type] = frozenset({
        ast.Place, ast.Hole, ast.Translate, ast.Grid, ast.Polar,
    })

    def _gen_pipe_op(self, current: str, op: ast.Node, prev_op: ast.Node | None = None, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        # Insert implicit workplane when going from Face selection to 2D primitive
        if isinstance(op, ast.Implicit2DPrimitive) and isinstance(prev_op, ast.FacesSelect):
            current = f"{current}.workplane()"

        handler_name = self._PIPE_DISPATCH.get(type(op))
        if handler_name is None:
            raise CodegenError(f"Unknown pipe operation: {type(op).__name__}")

        handler = getattr(self, handler_name)
        if type(op) in self._PIPE_CTX_OPS:
            return handler(current, op, ctx=ctx)
        return handler(current, op)

    def _gen_pipe_fillet(self, current: str, op: ast.Fillet) -> str:
        return f"{current}.fillet({self._gen_expr(op.radius)})"

    def _gen_pipe_chamfer(self, current: str, op: ast.Chamfer) -> str:
        return f"{current}.chamfer({self._gen_expr(op.radius)})"

    def _gen_pipe_grid(self, current: str, op: ast.Grid, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        if ctx in (PipelineContext.FACE_SELECTION, PipelineContext.POINT_SELECTION):
            return self._gen_grid_on_face(current, op, ctx)
        return self._gen_grid_placement(current, op)

    def _gen_pipe_polar_op(self, current: str, op: ast.Polar, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        if ctx in (PipelineContext.FACE_SELECTION, PipelineContext.POINT_SELECTION):
            return self._gen_polar_on_face(current, op, ctx)
        return self._gen_polar_placement(current, op)

    # --- Center kwarg helper ---

    def _gen_centered_arg(self, center_node: ast.Node | None, ndim: int = 3) -> str:
        """Generate the centered argument string for primitives.

        Returns empty string if center is None (default centered=True).
        For BoolConst, returns the appropriate tuple.
        For TupleLit, generates per-axis values.
        """
        if center_node is None:
            return ""
        if isinstance(center_node, ast.BoolConst):
            if ndim == 3:
                val = "True" if center_node.value else "False"
                return f", centered=({val}, {val}, {val})"
            else:
                val = "True" if center_node.value else "False"
                return f", centered=({val}, {val})"
        if isinstance(center_node, ast.TupleLit):
            vals = [self._gen_expr(v) for v in center_node.values]
            return f", centered=({', '.join(vals)})"
        # Expression (e.g. variable): evaluate at runtime
        return f", centered={self._gen_expr(center_node)}"

    # --- 3D Primitives ---

    def _gen_box(self, node: ast.Box) -> str:
        w = self._gen_expr(node.width)
        h = self._gen_expr(node.height)
        d = self._gen_expr(node.depth)
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").box({w}, {h}, {d}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_cylinder(self, node: ast.Cylinder) -> str:
        h = self._gen_expr(node.height)
        r = self._gen_expr(node.radius)
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").cylinder({r}, {h}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_sphere(self, node: ast.Sphere) -> str:
        r = self._gen_expr(node.radius)
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").sphere({r}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_cone(self, node: ast.Cone) -> str:
        h = self._gen_expr(node.height)
        r1 = self._gen_expr(node.r1)
        r2 = self._gen_expr(node.r2)
        extras = ""
        if node.pnt:
            extras += f", pnt={self._gen_expr(node.pnt)}"
        if node.dir:
            extras += f", dir={self._gen_expr(node.dir)}"
        if node.angle:
            extras += f", angle={self._gen_expr(node.angle)}"
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").cone({r1}, {r2}, {h}{extras}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_torus(self, node: ast.Torus) -> str:
        r1 = self._gen_expr(node.r1)
        r2 = self._gen_expr(node.r2)
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").torus({r1}, {r2}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_wedge(self, node: ast.Wedge) -> str:
        dx = self._gen_expr(node.dx)
        dy = self._gen_expr(node.dy)
        dz = self._gen_expr(node.dz)
        ltx = self._gen_expr(node.ltx)
        centered = self._gen_centered_arg(node.center, ndim=3)
        code = f'cq.Workplane("XY").wedge({dx}, {dy}, {dz}, {ltx}{centered})'
        return self._gen_at_kwarg(code, node.at)

    # --- 2D Primitives ---

    def _gen_rect(self, node: ast.Rect) -> str:
        w = self._gen_expr(node.width)
        h = self._gen_expr(node.height)
        centered = self._gen_centered_arg(node.center, ndim=2)
        code = f'cq.Workplane("XY").rect({w}, {h}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_circle(self, node: ast.Circle) -> str:
        r = self._gen_expr(node.radius)
        centered = self._gen_centered_arg(node.center, ndim=2)
        code = f'cq.Workplane("XY").circle({r}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_ellipse(self, node: ast.Ellipse) -> str:
        rx = self._gen_expr(node.rx)
        ry = self._gen_expr(node.ry)
        centered = self._gen_centered_arg(node.center, ndim=2)
        code = f'cq.Workplane("XY").ellipse({rx}, {ry}{centered})'
        return self._gen_at_kwarg(code, node.at)

    def _gen_polyline(self, node: ast.Polyline) -> str:
        pts = self._gen_expr(node.points)
        return f'cq.Workplane("XY").polyline({pts}).close()'

    def _gen_polygon(self, node: ast.Polygon) -> str:
        n = self._gen_expr(node.n)
        r = self._gen_expr(node.r)
        return f'cq.Workplane("XY").polygon({n}, {r})'

    def _gen_text(self, node: ast.Text) -> str:
        content = self._gen_expr(node.content)
        size = self._gen_expr(node.size) if node.size else "10"
        return f'cq.Workplane("XY").text({content}, {size}, 1)'

    # --- Sketch ---

    def _gen_sketch(self, node: ast.SketchExpr) -> str:
        return self._gen_sketch_segments('cq.Workplane("XY")', node)

    def _gen_sketch_segments(self, current: str, node: ast.SketchExpr) -> str:
        """Generate sketch(...) call with segments on the given workplane expression."""
        start = self._gen_expr(node.start)
        parts = [f'{current}.sketch({start}']
        for seg in node.segments:
            if isinstance(seg, ast.TupleLit):
                pt = self._gen_expr(seg)
                parts.append(f', ("line", {pt})')
            elif isinstance(seg, ast.ArcPath):
                through = self._gen_expr(seg.through)
                end = self._gen_expr(seg.end)
                parts.append(f', ("arc", {through}, {end})')
            elif isinstance(seg, ast.BezierPath):
                pts = self._gen_expr(seg.points)
                parts.append(f', ("bezier", {pts})')
        parts.append(")")
        return "".join(parts)

    # --- Path Primitives ---

    def _gen_line_path(self, node: ast.LinePath) -> str:
        s = self._gen_expr(node.start)
        e = self._gen_expr(node.end)
        return f'cq.Workplane("XY").moveTo({s}[0], {s}[1]).lineTo({e}[0], {e}[1])'

    def _gen_arc_path(self, node: ast.ArcPath) -> str:
        # Simplified arc generation
        t = self._gen_expr(node.through)
        e = self._gen_expr(node.end)
        return f'.threePointArc({t}, {e})'

    def _gen_helix_path(self, node: ast.HelixPath) -> str:
        pitch = self._gen_expr(node.pitch)
        h = self._gen_expr(node.height)
        r = self._gen_expr(node.radius)
        return f'cq.Wire.makeHelix(pitch={pitch}, height={h}, radius={r})'

    def _gen_bezier_path(self, node: ast.BezierPath) -> str:
        pts = self._gen_expr(node.points)
        return f'cq.Workplane("XY").spline({pts})'

    def _gen_spline_path(self, node: ast.SplinePath) -> str:
        pts = self._gen_expr(node.points)
        return f'cq.Workplane("XY").spline({pts})'

    # --- Pipe Operations ---

    def _gen_selector_arg(self, op) -> str | None:
        """Generate a selector string.
        Multiple selectors → AND (join with ' and ').
        Single list selector → OR (join with ' or ')."""
        if op.selectors:
            parts = [self._gen_expr(s) for s in op.selectors]
            return ' + " and " + '.join(parts)
        if op.selector is not None:
            # List literal → OR: edges [>Z, >X]
            if isinstance(op.selector, ast.ListLit):
                parts = [self._gen_expr(v) for v in op.selector.values]
                return ' + " or " + '.join(parts)
            return self._gen_expr(op.selector)
        return None

    def _gen_faces_select(self, current: str, op: ast.FacesSelect) -> str:
        if isinstance(op.selector, ast.TagRef):
            return f'{current}.faces(tag="{op.selector.name}")'
        sel = self._gen_selector_arg(op)
        if op.tag:
            var = self._new_var()
            self._emit(f'{var} = {current}.tag("{op.tag}")')
            return f'{var}.faces({sel})'
        return f'{current}.faces({sel})'

    def _gen_edges_select(self, current: str, op: ast.EdgesSelect) -> str:
        if isinstance(op.selector, ast.TagRef):
            return f'{current}.edges(tag="{op.selector.name}")'
        sel = self._gen_selector_arg(op)
        if op.tag:
            var = self._new_var()
            self._emit(f'{var} = {current}.tag("{op.tag}")')
            return f'{var}.edges({sel})'
        return f'{current}.edges({sel})'

    def _gen_vertices_select(self, current: str, op: ast.VerticesSelect) -> str:
        if isinstance(op.selector, ast.TagRef):
            return f'{current}.vertices(tag="{op.selector.name}")'
        sel = self._gen_selector_arg(op)
        if sel is not None:
            if op.tag:
                var = self._new_var()
                self._emit(f'{var} = {current}.tag("{op.tag}")')
                return f'{var}.vertices({sel})'
            return f'{current}.vertices({sel})'
        else:
            if op.tag:
                var = self._new_var()
                self._emit(f'{var} = {current}.tag("{op.tag}")')
                return f'{var}.vertices()'
            return f'{current}.vertices()'

    def _gen_points_select(self, current: str, op: ast.PointsSelect) -> str:
        spec = op.spec
        if isinstance(spec, ast.Polar):
            n = self._gen_expr(spec.count)
            r = self._gen_expr(spec.radius)
            var = self._new_var()
            self._emit(f'{var}_pts = [({r} * math.cos(2 * math.pi * i / {n}), {r} * math.sin(2 * math.pi * i / {n})) for i in range({n})]')
            return f'{current}.workplane().pushPoints({var}_pts)'
        elif isinstance(spec, ast.Grid):
            nx = self._gen_expr(spec.nx)
            ny = self._gen_expr(spec.ny)
            sp = self._gen_expr(spec.spacing)
            return f'{current}.workplane().rarray({sp}, {sp}, {nx}, {ny})'
        elif isinstance(spec, ast.ListLit):
            pts = self._gen_expr(spec)
            return f'{current}.workplane().pushPoints({pts})'
        else:
            pts = self._gen_expr(spec)
            return f'{current}.workplane().pushPoints({pts})'

    # Rotation angles (degrees) to transform from default XY workplane to target plane
    _PLANE_ROTATIONS = {
        "XZ": "(-90, 0, 0)",
        "YZ": "(0, 90, 0)",
        "ZX": "(0, -90, 0)",
        "ZY": "(90, 0, 0)",
        "YX": "(0, 0, -90)",
    }

    def _gen_workplane(self, current: str, op: ast.Workplane) -> str:
        if op.plane:
            rotation = self._PLANE_ROTATIONS.get(op.plane)
            if rotation:
                return f'{current}.workplane().transformed(rotate={rotation})'
            # XY or unknown plane: just use default workplane
            return f'{current}.workplane()'
        return f'{current}.workplane()'

    def _gen_as_tag(self, current: str, op: ast.AsTag) -> str:
        return f'{current}.tag("{op.name}")'

    def _gen_shell(self, current: str, op: ast.Shell) -> str:
        t = self._gen_expr(op.thickness)
        return f'{current}.shell({t})'

    def _gen_offset(self, current: str, op: ast.Offset) -> str:
        d = self._gen_expr(op.distance)
        return f'{current}.offset({d})'

    def _gen_diff(self, current: str, op: ast.Diff) -> str:
        if isinstance(op.shape, ast.ListLit):
            var = self._new_var()
            self._emit(f"{var} = {current}")
            for item in op.shape.values:
                item_code = self._gen_expr(item)
                self._emit(f"{var} = {var}.cut({item_code})")
            return var
        shape = self._gen_expr(op.shape)
        return f'{current}.cut({shape})'

    def _gen_union(self, current: str, op: ast.Union) -> str:
        if isinstance(op.shape, ast.ListLit):
            var = self._new_var()
            self._emit(f"{var} = {current}")
            for item in op.shape.values:
                item_code = self._gen_expr(item)
                self._emit(f"{var} = {var}.union({item_code})")
            return var
        shape = self._gen_expr(op.shape)
        return f'{current}.union({shape})'

    def _gen_inter(self, current: str, op: ast.Inter) -> str:
        if isinstance(op.shape, ast.ListLit):
            var = self._new_var()
            self._emit(f"{var} = {current}")
            for item in op.shape.values:
                item_code = self._gen_expr(item)
                self._emit(f"{var} = {var}.intersect({item_code})")
            return var
        shape = self._gen_expr(op.shape)
        return f'{current}.intersect({shape})'

    def _gen_place(self, current: str, op: ast.Place, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        if ctx in (PipelineContext.THREE_D, PipelineContext.EDGE_SELECTION):
            raise CodegenError(
                "'place' requires face selection or workplane context. "
                "Use '| faces top |' or similar before '| place ...'"
            )
        shape = self._gen_expr(op.shape)
        # If coming from face selection, insert implicit workplane
        if ctx == PipelineContext.FACE_SELECTION:
            return f'{current}.workplane().place({shape})'
        return f'{current}.place({shape})'

    def _gen_hole(self, current: str, op: ast.Hole, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        r = self._gen_expr(op.radius)
        if ctx == PipelineContext.FACE_SELECTION:
            # FaceSelection -> hole: cut at centre of each selected face
            if op.depth:
                depth = self._gen_expr(op.depth)
                return f'{current}.holeOnFaces({r}, {depth})'
            return f'{current}.holeOnFaces({r})'
        if op.depth:
            depth = self._gen_expr(op.depth)
            return f'{current}.hole({r} * 2, {depth})'
        return f'{current}.hole({r} * 2)'

    def _gen_cut(self, current: str, op: ast.Cut) -> str:
        if op.depth:
            depth = self._gen_expr(op.depth)
            return f'{current}.cutBlind(-{depth})'
        return f'{current}.cutThruAll()'

    def _gen_extrude(self, current: str, op: ast.Extrude) -> str:
        h = self._gen_expr(op.height)
        if op.draft:
            draft = self._gen_expr(op.draft)
            return f'{current}.extrude({h}, taper={draft})'
        return f'{current}.extrude({h})'

    def _gen_revolve(self, current: str, op: ast.Revolve) -> str:
        deg = self._gen_expr(op.degrees)
        if op.axis:
            axis_map = {"X": "(1,0,0)", "Y": "(0,1,0)", "Z": "(0,0,1)"}
            end = axis_map.get(op.axis.upper(), "(0,1,0)")
            return f'{current}.revolve({deg}, axisStart=(0,0,0), axisEnd={end})'
        return f'{current}.revolve({deg})'

    def _gen_sweep(self, current: str, op: ast.Sweep) -> str:
        path = self._gen_expr(op.path)
        return f'{current}.sweep({path})'

    def _gen_loft(self, current: str, op: ast.Loft) -> str:
        sections = self._gen_expr(op.sections)
        args = [sections]
        kwargs = []
        if op.height is not None:
            h_code = self._gen_expr(op.height)
            if isinstance(op.height, ast.ListLit):
                kwargs.append(f'heights={h_code}')
            else:
                args.append(h_code)
        if op.ruled:
            kwargs.append('ruled=True')
        all_args = ', '.join(args + kwargs)
        return f'{current}.loft({all_args})'

    def _gen_color(self, current: str, op: ast.ColorOp) -> str:
        """Generate color metadata attachment.

        Color is stored as metadata on the shape for later use in export.
        At the CadQuery/OCP level, we use a wrapper that attaches color info.
        """
        args = op.args
        named = op.named_args
        alpha = named.get("alpha")
        alpha_str = self._gen_expr(alpha) if alpha else "1.0"

        if len(args) == 1 and isinstance(args[0], ast.StringLit):
            # Named color or HEX: resolve at compile time
            color_str = args[0].value
            rgb = resolve_color(color_str)
            r, g, b = rgb
            return (
                f'{current}.setColor({r}, {g}, {b}, {alpha_str})'
            )
        elif len(args) == 3:
            # RGB numeric: resolve at runtime (values might be expressions)
            r = self._gen_expr(args[0])
            g = self._gen_expr(args[1])
            b = self._gen_expr(args[2])
            # Normalize: if any > 1, divide all by 255
            var = self._new_var()
            self._emit(f'{var}_r, {var}_g, {var}_b = ({r}), ({g}), ({b})')
            self._emit(f'if {var}_r > 1 or {var}_g > 1 or {var}_b > 1:')
            self.indent += 1
            self._emit(f'{var}_r, {var}_g, {var}_b = {var}_r / 255, {var}_g / 255, {var}_b / 255')
            self.indent -= 1
            return (
                f'{current}.setColor({var}_r, {var}_g, {var}_b, {alpha_str})'
            )
        else:
            raise CodegenError("color requires a color name string or 3 RGB values")

    def _gen_rotate(self, current: str, op: ast.Rotate) -> str:
        angles = op.angles
        origin = op.origin
        origin_expr = self._resolve_origin(current, origin)

        if isinstance(angles, ast.TupleLit) and len(angles.values) == 3:
            ax = self._gen_expr(angles.values[0])
            ay = self._gen_expr(angles.values[1])
            az = self._gen_expr(angles.values[2])
            result = current
            if ax != "0":
                result = f'{result}.rotate({origin_expr}, (1,0,0), {ax})'
            if ay != "0":
                result = f'{result}.rotate({origin_expr}, (0,1,0), {ay})'
            if az != "0":
                result = f'{result}.rotate({origin_expr}, (0,0,1), {az})'
            return result
        return f'{current}.rotate({origin_expr}, (0,0,1), 0)'

    def _gen_translate(self, current: str, op: ast.Translate, ctx: PipelineContext = PipelineContext.UNKNOWN) -> str:
        origin = op.origin
        vec = self._gen_expr(op.vector)

        # In VertexSelection/PointSelection context, translate the points
        if ctx in (PipelineContext.VERTEX_SELECTION, PipelineContext.POINT_SELECTION):
            return f'{current}.translate_points({vec})'

        if origin is None or (isinstance(origin, ast.StringLit) and origin.value == "world"):
            return f'{current}.translate({vec})'
        elif isinstance(origin, ast.StringLit) and origin.value == "local":
            # Move center to origin, translate, move back
            var = self._new_var()
            self._emit(f'{var}_bb = {current}.val().BoundingBox()')
            self._emit(f'{var}_center = (({var}_bb.xmin + {var}_bb.xmax) / 2, ({var}_bb.ymin + {var}_bb.ymax) / 2, ({var}_bb.zmin + {var}_bb.zmax) / 2)')
            self._emit(f'{var}_neg_center = (-{var}_center[0], -{var}_center[1], -{var}_center[2])')
            self._emit(f'{var} = {current}.translate({var}_neg_center).translate({vec}).translate({var}_center)')
            return var
        elif isinstance(origin, ast.TupleLit):
            # Move to specified origin, translate, move back
            origin_expr = self._gen_expr(origin)
            var = self._new_var()
            self._emit(f'{var}_origin = {origin_expr}')
            self._emit(f'{var}_neg = (-{var}_origin[0], -{var}_origin[1], -{var}_origin[2])')
            self._emit(f'{var} = {current}.translate({var}_neg).translate({vec}).translate({var}_origin)')
            return var
        else:
            return f'{current}.translate({vec})'

    def _gen_scale(self, current: str, op: ast.Scale) -> str:
        vector = op.vector
        origin = op.origin

        # Determine scale factors
        if isinstance(vector, ast.TupleLit):
            vals = vector.values
            if len(vals) == 1:
                # Uniform scale
                s = self._gen_expr(vals[0])
                sx = sy = sz = s
            elif len(vals) == 3:
                sx = self._gen_expr(vals[0])
                sy = self._gen_expr(vals[1])
                sz = self._gen_expr(vals[2])
            else:
                raise CodegenError(f"scale requires 1 or 3 arguments, got {len(vals)}")
        else:
            raise CodegenError("scale requires numeric arguments")

        # Resolve origin point
        if origin is None or (isinstance(origin, ast.StringLit) and origin.value == "world"):
            origin_expr = "(0,0,0)"
        elif isinstance(origin, ast.StringLit) and origin.value == "local":
            var = self._new_var()
            self._emit(f'{var}_bb = {current}.val().BoundingBox()')
            self._emit(f'{var}_center = (({var}_bb.xmin + {var}_bb.xmax) / 2, ({var}_bb.ymin + {var}_bb.ymax) / 2, ({var}_bb.zmin + {var}_bb.zmax) / 2)')
            origin_expr = f'{var}_center'
        elif isinstance(origin, ast.TupleLit):
            origin_expr = self._gen_expr(origin)
        else:
            origin_expr = "(0,0,0)"

        return f'{current}.scale({sx}, {sy}, {sz}, {origin_expr})'

    def _resolve_origin(self, current: str, origin) -> str:
        """Resolve origin for rotate operations. Returns a string expression for the origin point."""
        if origin is None or (isinstance(origin, ast.StringLit) and origin.value == "world"):
            return "(0,0,0)"
        elif isinstance(origin, ast.StringLit) and origin.value == "local":
            var = self._new_var()
            self._emit(f'{var}_bb = {current}.val().BoundingBox()')
            self._emit(f'{var}_center = (({var}_bb.xmin + {var}_bb.xmax) / 2, ({var}_bb.ymin + {var}_bb.ymax) / 2, ({var}_bb.zmin + {var}_bb.zmax) / 2)')
            return f'{var}_center'
        elif isinstance(origin, ast.TupleLit):
            return self._gen_expr(origin)
        else:
            return "(0,0,0)"

    def _gen_mirror(self, current: str, op: ast.Mirror) -> str:
        axis = op.axis or "X"
        ax = axis.upper()
        if ax == "X":
            return f'{current}.mirror("YZ")'
        elif ax == "Y":
            return f'{current}.mirror("XZ")'
        elif ax == "Z":
            return f'{current}.mirror("XY")'
        return f'{current}.mirror("YZ")'

    def _gen_move(self, current: str, op: ast.Move) -> str:
        if isinstance(op.offset, ast.TupleLit) and len(op.offset.values) >= 2:
            x = self._gen_expr(op.offset.values[0])
            y = self._gen_expr(op.offset.values[1])
            return f'{current}.center({x}, {y})'
        return current

    def _gen_moveto(self, current: str, op: ast.MoveTo) -> str:
        if isinstance(op.position, ast.TupleLit) and len(op.position.values) >= 2:
            x = self._gen_expr(op.position.values[0])
            y = self._gen_expr(op.position.values[1])
            return f'{current}.moveTo({x}, {y})'
        return current

    def _gen_implicit_2d(self, current: str, op: ast.Implicit2DPrimitive) -> str:
        prim = op.primitive
        if isinstance(prim, ast.Rect):
            w = self._gen_expr(prim.width)
            h = self._gen_expr(prim.height)
            centered = self._gen_centered_arg(prim.center, ndim=2)
            return f'{current}.rect({w}, {h}{centered})'
        elif isinstance(prim, ast.Circle):
            r = self._gen_expr(prim.radius)
            centered = self._gen_centered_arg(prim.center, ndim=2)
            return f'{current}.circle({r}{centered})'
        elif isinstance(prim, ast.Ellipse):
            rx = self._gen_expr(prim.rx)
            ry = self._gen_expr(prim.ry)
            centered = self._gen_centered_arg(prim.center, ndim=2)
            return f'{current}.ellipse({rx}, {ry}{centered})'
        elif isinstance(prim, ast.Polyline):
            pts = self._gen_expr(prim.points)
            return f'{current}.polyline({pts}).close()'
        elif isinstance(prim, ast.Polygon):
            n = self._gen_expr(prim.n)
            r = self._gen_expr(prim.r)
            return f'{current}.polygon({n}, {r})'
        elif isinstance(prim, ast.Text):
            content = self._gen_expr(prim.content)
            size = self._gen_expr(prim.size) if prim.size else "10"
            return f'{current}.text({content}, {size}, 1)'
        elif isinstance(prim, ast.SketchExpr):
            return self._gen_sketch_segments(current, prim)
        else:
            raise CodegenError(f"Cannot use {type(prim).__name__} as implicit 2D in pipe")

    def _gen_implicit_3d(self, current: str, op: ast.Implicit3DPrimitive) -> str:
        prim = op.primitive
        if isinstance(prim, ast.Box):
            w = self._gen_expr(prim.width)
            h = self._gen_expr(prim.height)
            d = self._gen_expr(prim.depth)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").box({w}, {h}, {d}{centered}))'
        elif isinstance(prim, ast.Cylinder):
            ht = self._gen_expr(prim.height)
            r = self._gen_expr(prim.radius)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").cylinder({r}, {ht}{centered}))'
        elif isinstance(prim, ast.Sphere):
            r = self._gen_expr(prim.radius)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").sphere({r}{centered}))'
        elif isinstance(prim, ast.Cone):
            ht = self._gen_expr(prim.height)
            r1 = self._gen_expr(prim.r1)
            r2 = self._gen_expr(prim.r2)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").cone({r1}, {r2}, {ht}{centered}))'
        elif isinstance(prim, ast.Torus):
            r1 = self._gen_expr(prim.r1)
            r2 = self._gen_expr(prim.r2)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").torus({r1}, {r2}{centered}))'
        elif isinstance(prim, ast.Wedge):
            dx = self._gen_expr(prim.dx)
            dy = self._gen_expr(prim.dy)
            dz = self._gen_expr(prim.dz)
            ltx = self._gen_expr(prim.ltx)
            centered = self._gen_centered_arg(prim.center, ndim=3)
            return f'{current}.place_3d_at_points(lambda: cq.Workplane("XY").wedge({dx}, {dy}, {dz}, {ltx}{centered}))'
        else:
            raise CodegenError(f"Cannot use {type(prim).__name__} as implicit 3D in pipe")

    # --- Source commands: union/diff/inter with list ---

    def _gen_bool_source(self, node, method: str) -> str:
        """Generate code for union/diff/inter as source commands with a list argument."""
        shape = node.shape
        if isinstance(shape, ast.ListLit) and shape.values:
            var = self._new_var()
            first = self._gen_expr(shape.values[0])
            self._emit(f"{var} = {first}")
            for item in shape.values[1:]:
                item_code = self._gen_expr(item)
                self._emit(f"{var} = {var}.{method}({item_code})")
            return var
        # Single shape or variable — evaluate directly
        return self._gen_expr(shape)

    def _gen_union_source(self, node: ast.Union) -> str:
        return self._gen_bool_source(node, "union")

    def _gen_diff_source(self, node: ast.Diff) -> str:
        return self._gen_bool_source(node, "cut")

    def _gen_inter_source(self, node: ast.Inter) -> str:
        return self._gen_bool_source(node, "intersect")

    # --- List Comprehension ---

    def _gen_list_comp(self, node: ast.ListComp) -> str:
        expr = self._gen_expr(node.expr)
        var = node.var
        iter_expr = self._gen_expr(node.iter_expr)
        return f"[{expr} for {var} in range({iter_expr})]"

    # --- Function Call ---

    def _gen_func_call(self, node: ast.FuncCall) -> str:
        name = node.name
        # Map math functions to math module
        if name in _MATH_ALIASES:
            name = f"math.{_MATH_ALIASES[name]}"
        elif name in _MATH_FUNCS:
            name = f"math.{name}"
        args = ", ".join(self._gen_expr(a) for a in node.args)
        # Extract at: for post-call placement
        at_node = node.kwargs.get("at")
        func_kwargs = {k: v for k, v in node.kwargs.items() if k != "at"}
        kwargs = ", ".join(f"{k}={self._gen_expr(v)}" for k, v in func_kwargs.items())
        all_args = ", ".join(filter(None, [args, kwargs]))
        code = f"{name}({all_args})"
        if at_node is not None:
            # Runtime guard: only apply at: if result is a shape (has .translate)
            var = self._new_var()
            self._emit(f'{var} = {code}')
            placed = self._gen_at_kwarg(var, at_node)
            if placed != var:
                return f'({placed} if hasattr({var}, "translate") else {var})'
            return var
        return code

    # --- At Placement ---

    def _gen_at_kwarg(self, shape_code: str, at_node: ast.Node | None) -> str:
        """Apply at: kwarg translation if present."""
        if at_node is None:
            return shape_code
        if isinstance(at_node, ast.TupleLit):
            return self._gen_translate_tuple(shape_code, at_node)
        elif isinstance(at_node, ast.ListLit):
            return self._gen_list_placement(shape_code, at_node)
        else:
            # Single value — treat as x offset
            val = self._gen_expr(at_node)
            return f'{shape_code}.translate(({val}, 0, 0))'

    def _gen_translate_tuple(self, shape_code: str, tup: ast.TupleLit) -> str:
        vals = [self._gen_expr(v) for v in tup.values]
        if len(vals) == 2:
            return f'{shape_code}.translate(({vals[0]}, {vals[1]}, 0))'
        elif len(vals) == 3:
            return f'{shape_code}.translate(({vals[0]}, {vals[1]}, {vals[2]}))'
        return shape_code

    def _gen_polar_placement(self, shape_code: str, polar: ast.Polar) -> str:
        n = self._gen_expr(polar.count)
        r = self._gen_expr(polar.radius)
        return f'{shape_code}.polar({n}, {r})'

    def _gen_polar_on_face(self, shape_code: str, polar: ast.Polar, ctx: PipelineContext) -> str:
        n = self._gen_expr(polar.count)
        r = self._gen_expr(polar.radius)
        wp = f'{shape_code}.workplane()' if ctx == PipelineContext.FACE_SELECTION else shape_code
        return f'{wp}.pushPoints([({r}*math.cos(2*math.pi*i/{n}), {r}*math.sin(2*math.pi*i/{n})) for i in range({n})])'

    def _gen_grid_placement(self, shape_code: str, grid: ast.Grid) -> str:
        nx = self._gen_expr(grid.nx)
        ny = self._gen_expr(grid.ny)
        sp = self._gen_expr(grid.spacing)
        return f'{shape_code}.grid({nx}, {ny}, {sp})'

    def _gen_grid_on_face(self, shape_code: str, grid: ast.Grid, ctx: PipelineContext) -> str:
        nx = self._gen_expr(grid.nx)
        ny = self._gen_expr(grid.ny)
        sp = self._gen_expr(grid.spacing)
        wp = f'{shape_code}.workplane()' if ctx == PipelineContext.FACE_SELECTION else shape_code
        return f'{wp}.pushPoints([({sp}*ix - ({nx}-1)*{sp}/2, {sp}*iy - ({ny}-1)*{sp}/2) for iy in range({ny}) for ix in range({nx})])'

    def _gen_list_placement(self, shape_code: str, lst: ast.ListLit) -> str:
        var = self._new_var()
        self._emit(f'{var} = {shape_code}')
        result = self._new_var()
        self._emit(f'{result} = None')
        for i, pos in enumerate(lst.values):
            pos_code = self._gen_expr(pos)
            if isinstance(pos, ast.TupleLit) and len(pos.values) == 2:
                tx = self._gen_expr(pos.values[0])
                ty = self._gen_expr(pos.values[1])
                t = f'({tx}, {ty}, 0)'
            else:
                t = pos_code
            self._emit(f'_copy = {var}.translate({t})')
            if i == 0:
                self._emit(f'{result} = _copy')
            else:
                self._emit(f'{result} = {result}.union(_copy)')
        return result


def generate(program: ast.Program) -> str:
    """Generate OCP Python code from a PolyScript AST."""
    gen = OCPCodegen()
    return gen.generate(program)
