"""Tests for error handling."""

import pytest
from polyscript.errors import ParseError
from polyscript.executor import compile_source


class TestParseErrors:
    def test_invalid_syntax(self):
        with pytest.raises(ParseError):
            compile_source("box(")

    def test_unknown_pipe_op(self):
        with pytest.raises(ParseError):
            compile_source("box 10 10 10 | nonexistent 5")


class TestCodeOutput:
    def test_generates_header(self):
        code = compile_source("box 10 10 10")
        assert '# Generated by PolyScript' in code
        assert 'ocp_kernel as cq' in code
        assert 'import math' in code

    def test_result_var(self):
        code = compile_source("box 10 10 10")
        assert '_result' in code

    def test_no_geometry(self):
        """Assignment-only code produces _result = None (no shape expression)."""
        code = compile_source("$x = 10")
        assert '_result = None' in code
